// Alle combinaties:
// days: [Ma wel/niet; Di wel/niet; Wo wel/niet; Do wel/niet; Vr wel/niet; Za wel/niet; Zo wel/niet;]
// givenSets = [1-25, 26-50, 51-59, 60-75, 76-100, 101-118, 119-128]
// givenFreq = [1,2,3]
const List<Step6TestCase> step6TestCases = [
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "1-25",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "1-25",
    givenFreq: "2",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "1-25",
    givenFreq: "3",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "26-50",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "26-50",
    givenFreq: "2",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "26-50",
    givenFreq: "3",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "51-59",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "51-59",
    givenFreq: "2",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "51-59",
    givenFreq: "3",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "60-75",
    givenFreq: "2",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "60-75",
    givenFreq: "3",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "24-50",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "24-50",
    givenFreq: "2",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "24-50",
    givenFreq: "3",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "51-59",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "51-59",
    givenFreq: "2",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "51-59",
    givenFreq: "3",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "60-75",
    givenFreq: "2",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "60-75",
    givenFreq: "3",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Dinsdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "24-50",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "24-50",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "24-50",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "51-59",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "51-59",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "51-59",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "60-75",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "60-75",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "24-44",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "24-44",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "24-44",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "45-59",
    givenFreq: "1",
    expectedPattern: 'BCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "45-59",
    givenFreq: "2",
    expectedPattern: 'BCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "45-59",
    givenFreq: "3",
    expectedPattern: 'BCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "60-75",
    givenFreq: "2",
    expectedPattern: 'BCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "60-75",
    givenFreq: "3",
    expectedPattern: 'BCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'BCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'BCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "24-50",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "24-50",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "24-50",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "51-59",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "51-59",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "51-59",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "60-75",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "60-75",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Donderdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "24-43",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "24-43",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "24-43",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "44-59",
    givenFreq: "1",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "44-59",
    givenFreq: "2",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "44-59",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "60-75",
    givenFreq: "2",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "60-75",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "24-47",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "24-47",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "24-47",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "48-59",
    givenFreq: "1",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "48-59",
    givenFreq: "2",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "48-59",
    givenFreq: "3",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "60-75",
    givenFreq: "2",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "60-75",
    givenFreq: "3",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "24-43",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "24-43",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "24-43",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "44-59",
    givenFreq: "1",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Vrijdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "44-59",
    givenFreq: "2",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Vrijdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "44-59",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Vrijdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "60-75",
    givenFreq: "2",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "60-75",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Vrijdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "24-40",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "24-40",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "24-40",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "41-59",
    givenFreq: "1",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "41-59",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "41-59",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "60-75",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "60-75",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Woensdag', 'Vrijdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "24-40",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "24-40",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "24-40",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "41-59",
    givenFreq: "1",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "41-60",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "41-60",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "61-75",
    givenFreq: "2",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "61-75",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "24-47",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "24-47",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "24-47",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "48-59",
    givenFreq: "1",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "48-59",
    givenFreq: "2",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "48-59",
    givenFreq: "3",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "60-75",
    givenFreq: "2",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "60-75",
    givenFreq: "3",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "24-40",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "24-40",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "24-40",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "41-59",
    givenFreq: "1",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "41-50",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "41-59",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "51-66",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "60-66",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "67-100",
    givenFreq: "2",
    expectedPattern: 'BCBCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "67-100",
    givenFreq: "3",
    expectedPattern: 'BCBCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCBCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCBCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCBCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "3",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "1",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Zaterdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "2",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Zaterdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Zaterdag'],
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "60-75",
    givenFreq: "2",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "60-75",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Zaterdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Woensdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "24-50",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "1",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "45-66",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "51-66",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "67-75",
    givenFreq: "2",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "67-75",
    givenFreq: "3",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "76-100",
    givenFreq: "2",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCBA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "24-50",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "1",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "51-59",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "60-66",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "60-66",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "67-100",
    givenFreq: "2",
    expectedPattern: 'BCAA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "67-100",
    givenFreq: "3",
    expectedPattern: 'BCAA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],,
  ),
  
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCAA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCAA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCAA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "1",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "60-66",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "60-66",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "67-100",
    givenFreq: "2",
    expectedPattern: 'BCBCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "67-100",
    givenFreq: "3",
    expectedPattern: 'BCBCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCBCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCBCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCBCA',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "1",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "60-66",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "60-66",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "67-100",
    givenFreq: "2",
    expectedPattern: 'BCBCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "67-100",
    givenFreq: "3",
    expectedPattern: 'BCBCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCBCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCBCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCBCB',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "24-44",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "1",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "45-59",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "60-80",
    givenFreq: "2",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "60-75",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "81-100",
    givenFreq: "2",
    expectedPattern: 'BCBCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "76-100",
    givenFreq: "3",
    expectedPattern: 'BCBCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCBCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCBCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCBCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "1-23",
    givenFreq: "1",
    expectedPattern: 'A',
    expectedPatternDays: ['Maandag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "1-23",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "1-23",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "24-44",
    givenFreq: "1",
    expectedPattern: 'BC',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "24-44",
    givenFreq: "2",
    expectedPattern: 'AA',
    expectedPatternDays: ['Maandag', 'Donderdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "24-44",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "45-59",
    givenFreq: "1",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "45-60",
    givenFreq: "2",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "45-59",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "61-80",
    givenFreq: "2",
    expectedPattern: 'BCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Donderdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "60-69",
    givenFreq: "3",
    expectedPattern: 'AAA',
    expectedPatternDays: ['Maandag', 'Woensdag', 'Vrijdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "81-100",
    givenFreq: "2",
    expectedPattern: 'BCBBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "70-100",
    givenFreq: "3",
    expectedPattern: 'BCBBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "101-118",
    givenFreq: "2",
    expectedPattern: 'BCBCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "101-118",
    givenFreq: "3",
    expectedPattern: 'BCBCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],,
  ),
  Step6TestCase(
    days: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'],
    givenSets: "119-128",
    givenFreq: "3",
    expectedPattern: 'BCBCBC',
    expectedPatternDays: ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],,
  ),
];