/**
 * Build script for Render.com static site.
 * Reads SUPABASE_URL, SUPABASE_ANON_KEY, APP_BASE_URL from environment
 * and writes js/config.js so the site works without committing secrets.
 * Also writes _redirects for Render routing (landing vs app-download links).
 */
const fs = require("fs");
const path = require("path");

const supabaseUrl = process.env.SUPABASE_URL || "";
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || "";
const appBaseUrl = process.env.APP_BASE_URL || "https://liftbetter.cloud/ref/";
const branchLinkBaseUrl = process.env.BRANCH_LINK_BASE_URL || "https://liftbetter.app.link";

const config = `window.AFFILIATE_CONFIG = {
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseAnonKey: ${JSON.stringify(supabaseAnonKey)},
  appBaseUrl: ${JSON.stringify(appBaseUrl)},
  branchLinkBaseUrl: ${JSON.stringify(branchLinkBaseUrl)},
};
`;

const outDir = path.join(__dirname, "..", "js");
const outPath = path.join(outDir, "config.js");
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outPath, config, "utf8");
console.log("Wrote js/config.js from environment variables.");

function writeRedirects() {
  const lines = [
    "# Auto-generated by scripts/render-build.js",
    "# Order matters: most specific rules first.",
    "",
    "# Affiliate promo landing page",
    "/join/:code  /index.html  200",
  ];

  if (supabaseUrl) {
    const redirectBase =
      supabaseUrl.replace(/\/$/, "") + "/functions/v1/affiliate-redirect";
    lines.push(
      "",
      "# App download links via Supabase affiliate-redirect",
      `/join  ${redirectBase}?code=join  302`,
      `/join/  ${redirectBase}?code=join  302`,
      `/website  ${redirectBase}?code=website  302`,
      `/website/  ${redirectBase}?code=website  302`,
      `/:code  ${redirectBase}?code=:code  302`
    );
  } else {
    lines.push(
      "",
      "# SUPABASE_URL missing at build time — app-link redirects not generated"
    );
  }

  const redirectsPath = path.join(__dirname, "..", "_redirects");
  fs.writeFileSync(redirectsPath, lines.join("\n") + "\n", "utf8");
  console.log("Wrote _redirects for Render routing.");
}

writeRedirects();
